<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-P4JKDR6" failures="2" tests="4" name="Test" time="1.12" errors="0" timestamp="2025-02-28T03:33:38 IST">
  <testcase classname="listerners.TestClass2" name="testMethod3" time="0.024">
    <failure type="java.lang.AssertionError" message="expected [TestNGListenersDemo] but found [TestNGListeners]">
      <![CDATA[java.lang.AssertionError: expected [TestNGListenersDemo] but found [TestNGListeners]
at listerners.TestClass2.testMethod3(TestClass2.java:22)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testMethod3 -->
  <testcase classname="listerners.TestClass2" name="testMethod1" time="0.002"/>
  <testcase classname="listerners.TestClass2" name="testMethod2" time="1.024">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method listerners.TestClass2.testMethod2() didn&amp;apos;t finish within the time-out 1000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method listerners.TestClass2.testMethod2() didn't finish within the time-out 1000
at java.base/java.lang.Thread.sleep0(Native Method)
at java.base/java.lang.Thread.sleep(Thread.java:509)
at listerners.TestClass2.testMethod2(TestClass2.java:16)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 6 stack frames]]>
    </failure>
  </testcase> <!-- testMethod2 -->
  <testcase classname="listerners.TestClass2" name="testMethod4" time="0.0">
    <skipped/>
  </testcase> <!-- testMethod4 -->
</testsuite> <!-- Test -->
